### PR TITLE
feat: add additional role based features

### LINKED ISSUE #156: Add role based features in ledger, cscc, create/recover dbs
add role based features in ledger, cscc, create/recover dbs

### PR DESCRIPTION
**Pull request by sudeshrshetty**
Added role based features in ledger storage, CSCC join chain, create
couch db, recover db

closed #156

Signed-off-by: sudesh.shetty <sudesh.shetty@securekey.com>

### CODE REVIEW

**Comment by sudeshrshetty** [comment]
verify-unitest

**Comment by bstasyszyn** [comment]
> I think this PR should be split into two: 1) move directories under storage and 2) adding role based features. It's difficult to see what code has changed and what has just been moved.

That's fine. I've reviewed it as is.

**Comment by sudeshrshetty** [comment]
verify-integration

**Comment by sudeshrshetty** [comment]
verify-integration

**Comment by sudeshrshetty** [comment]
verify-integration

**Pull request merged**
