### PR TITLE
chore: add Clean target

### PR DESCRIPTION
**Pull request by Baha-sk**
Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>

### CODE REVIEW

**Comment by troyronda** [comment]
This change needs to be updated with a semantic title.

**Comment by Baha-sk** [comment]
verify-unitest

**Comment by Baha-sk** [comment]
verify-unitest

**Comment by troyronda** [comment]
verify-unitest

**Comment by Baha-sk** [comment]
verify

**Comment by Baha-sk** [comment]
verify-unitest

**Pull request closed without merging**
